#!/bin/bash
source ./_lib
source ./_common
function _check {
  checkBin $1 || errorMessage "This tool requires <the_command>. Install it please, and then run this tool again."
}
if [[ $1 ]] ; then
    echo ""
else
    echo "Please pass argument one as _check function"
fi
if [[ $2  ]] ; then
    _check $2
else
    echo "Please pass argument two as the command you wish to check."
fi
