#!/usr/local/bin/bash
source ./_lib
source ./_common
function _install {
 if [[ $1 ]] ; then
     if test "$(uname -s)" = "Linux"; then
         `./homebrew/bin/brew install $1 `
     elif test "$(uname -s)" = "Darwin"; then
         `./homebrew/bin/brew install $1 `
     else
         scoop install $1 2> /dev/null
     fi
 else
      msg_status "⦊ You must pass something to install via brew i.e.- docker." "FAILED"
 fi
}
_install $1
