#!/usr/local/bin/bash

if [[ $1 == '-f' ]]; then
    shift
    echo "Forcing cache removal"
    if [ -d "./shc" ]; then
            echo "Clearing cached ./shc"
            rm -f $(pwd)/shc/bin-shc
            rmdir $(pwd)/shc
            echo "...done!"
        else
            echo "Filesystem ok..."
        fi
    fi
    if [ -r "./jq-osx-amd64" ]; then
        echo "Clearing cached ./jq-osx-amd64 binary"
            rm -f ./jq-osx-amd64
        echo "Proceeding..."
    fi

    if [ -d "./shc" ]; then
        echo "Remove the ./shc files? (y or n)"
        read answer
        if [ "$answer" != "${answer#[Yy]}" ] ; then
            echo "Attempting to remove ./shc"
            rm -f $(pwd)/shc/bin-shc
            rmdir $(pwd)/shc
        else
            echo "Filesystem ok..."
        fi
    fi
    if [ -r "./jq-osx-amd64" ]; then
        echo "Remove the ./jq-osx-amd64 binary? (y or n)"
        read answer
        if [ "$answer" != "${answer#[Yy]}" ] ; then
            rm -f ./jq-osx-amd64
        fi
    else
        echo "Proceeding..."
    fi
    mkdir -p ./shc
    curl -LO "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64"
    sudo chmod +x jq-osx-amd64
    sudo chmod 0777 jq-osx-amd64
    BIN_VERSION=$(curl -fsSL https://api.github.com/repos/neurobin/shc/releases/latest | ./jq-osx-amd64 -r .tag_name)
    echo "https://github.com/neurobin/shc/archive/refs/tags/${BIN_VERSION:-"4.0.3"}.tar.gz"
    curl -L "https://github.com/neurobin/shc/archive/refs/tags/${BIN_VERSION:-"4.0.3"}.tar.gz" -o ./shc-${BIN_VERSION:-"4.0.3"}.tar.gz
    tar -xvf ./shc-${BIN_VERSION:-"4.0.3"}.tar.gz
    eval "./_brew"
    pushd .
    ./_brew install gcc bazel
    cd ./shc-${BIN_VERSION:-\"4.0.3\"}
    ./configure --bindir=$(pwd) 
    make install
    cp shc ../shx
    popd
    eval "./shc $*"
    echo "attempting to remove files from cached directory"
    rm -rf ./shc
    rm -rf ./shc-${BIN_VERSION:-"4.0.3"} 
    echo "Finished, Goodbye!"
