#!/usr/bin/bash
declare -r DIR=$(cd "$(dirname pwd)")   # r.o. variable works in zsh and bash
declare -r dist="userland" # the type of distribution this is
declare -r mode="baseline" # which components to install
declare short_v="1.3"
source ../bin/lib
function efs_utils {
        echo "$1"
        DEBUG=n
        if test "$1" == "ubuntu"; then
        sudo apt-get update 2> /dev/null
        sudo apt-get -y install git binutils 2> /dev/null
        git clone https://github.com/aws/efs-utils 2> /dev/null
        cd efs-utils
        ./build-deb.sh 2> /dev/null
        sudo apt-get -y install ./build/amazon-efs-utils*deb 2> /dev/null

        msg_status "Installed Production Ubuntu Host EFS Tools" "PASSED"
    fi
    if test "$1" == "amazon-linux-2"; then
        brew install amazon-efs-utils
        sudo yum -y install wget
        if [[ "$(python3 -V 2>&1)" =~ ^(Python 3.6.*) ]]; then
            sudo wget https://bootstrap.pypa.io/pip/3.6/get-pip.py -O /tmp/get-pip.py
        elif [[ "$(python3 -V 2>&1)" =~ ^(Python 3.5.*) ]]; then
            sudo wget https://bootstrap.pypa.io/pip/3.5/get-pip.py -O /tmp/get-pip.py
        elif [[ "$(python3 -V 2>&1)" =~ ^(Python 3.4.*) ]]; then
            sudo wget https://bootstrap.pypa.io/pip/3.4/get-pip.py -O /tmp/get-pip.py
        else
            sudo wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
        fi
        echo ""
        msg_status "Installed Production Yum Host EFS Tools" "PASSED"
    fi
}

efs-utils 
